"""followers

Revision ID: 826e9472b3ea
Revises: a34249e161e3
Create Date: 2019-07-01 09:17:36.340321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826e9472b3ea'
down_revision = 'a34249e161e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
